apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-v1
  template:
    metadata:
      labels:
        app: portfolio-v1
    spec:
      containers:
        - image: mdfarhaan/portfolio-v1
          name: portfolio-v1

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-v1-service
spec:
  selector:
    app: portfolio-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
